### ISSUE TITLE
Error during registration in app

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/Info_tf-app#387]
Nick Hoar is trying to register, but after entering his email address he gets an error (see attachment). Deleted the app and tried again several times, no change. 
![img_1499](https://user-images.githubusercontent.com/31733464/51376286-3edefc00-1b08-11e9-8422-3dd29d56edda.PNG)

**Comment by lucasvanhalst** [comment]
When was this (16:53 in which timezone)? We had some issues since yesterday evening but they should be resolved now

**Comment by sabrinasadik** [comment]
China - was somewhere this morning

**Comment by lucasvanhalst** [comment]
Ok then it will work now
